# Generated by Django 5.1.1 on 2024-09-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
