# Generated by Django 5.1.1 on 2024-09-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestoreapp', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodel',
            fields=[
                ('adminemailid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adminpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailId', models.CharField(max_length=100)),
                ('ordernumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('phoneno', models.BigIntegerField()),
                ('totalbillamount', models.FloatField(default=0.0)),
            ],
        ),
    ]
